Always use the `"I"` format specifier for `size_t` with mingw (#14308)
* Always use the "I" format specifier for size_t with mingw

    runtime/domain.c:520:7: error: unknown conversion type character 'z'
    in format [-Werror=format=]
      520 |       "young_start: %p,"
          |       ^~~~~~~~~~~~~~~~~~
    In file included from runtime/domain.c:22:
    runtime/caml/config.h:71:35: note: format string is defined here
       71 | #define ARCH_SIZET_PRINTF_FORMAT "z"
          |                                   ^

In some configurations GCC will warn about "%z" not being supported.
Partially revert a change introduced in
295dd45852688c7c8b5df5e974c460588cdd9696.

> Some types are different sizes in 32-bit and 64-bit code. For
> example, size_t is 32 bits long in code compiled for x86, and 64
> bits in code compiled for x64. To create platform-agnostic
> formatting code for variable-width types, you can use a
> variable-width argument size modifier. Instead, use a 64-bit
> argument size modifier and explicitly promote the variable-width
> argument type to 64 bits. The Microsoft-specific I (uppercase i)
> argument size modifier handles variable-width integer arguments, but
> we recommend the type-specific j, t, and z modifiers for
> portability.

> Microsoft-specific:
> The I (uppercase i) […] argument size modifier prefix [is] Microsoft
> extension and is not ISO C-compatible.

https://learn.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-170#size

Presumably the GCC warning is outdated or erroneous, but there seem to
be no way around it.

* Update changes